# -*- coding: utf-8 -*-
"""SingleObj_train219_val99_1obj_r2 of GP.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1-O10lZsssQtVrHaf_OhpJtqijaYYMnUN
"""

from google.colab import drive

import pandas as pd
import operator
import numpy as np
from sklearn.metrics import r2_score
import random
import copy
import math
from scipy.stats import spearmanr
import matplotlib.pyplot as plt

drive.mount('/content/drive')

file_path = "/content/drive/My Drive/GWL/r2_complexity/train219_val99_1obj_r2 of GP/train219_dataset.csv"
df = pd.read_csv(file_path)


FEATURE_COLUMNS = ['Soil', 'Slope', 'Rain', 'LULC', 'Lithology','Lineament density', 'Geomorphology', 'Drainage density']
# #FEATURE_COLUMNS = ['geomorphology','Rain','drainage density']
TARGET_COLUMN = 'Net Groundwater Recharge'

X = df[FEATURE_COLUMNS].values
y = df[TARGET_COLUMN].values
validation_labels = df['validation point categorical data'].values



# Filter dataframe to use selected features
#df_filtered = df[FEATURE_COLUMNS + [TARGET_COLUMN]].copy()

# Optional: filter out extreme target values (e.g., outliers above 300)
#df_filtered = df_filtered[df_filtered[TARGET_COLUMN] < 300]

# Extract X and y
#X = df_filtered[FEATURE_COLUMNS].values
#y = df_filtered[TARGET_COLUMN].values

#Inspect shapes and first few rows
#print("Shape of X:", X.shape)
#print("Shape of y:", y.shape)
#print("Sample features (X):", X[:3])
#print("Sample target values (y):", y[:3])

# Mapping: x0 -> 'Soil', x1 -> 'Slope', etc.
symbolic_variable_map = {f'x{i}': FEATURE_COLUMNS[i] for i in range(len(FEATURE_COLUMNS))}

print("Symbolic Variable Mapping:")
for symbol, name in symbolic_variable_map.items():
     print(f"{symbol} → {name}")

#### Train "GW_potential_8Indicator_318pointsData.xls"

# drive.mount('/content/drive')
# file_path = "/content/drive/My Drive/GWL/r2_complexity/train219_val99_1obj_r2 of GP/GW_potential_8Indicator_318pointsData.xls"

# df = pd.read_excel(file_path)
# #df.head()

# print(df.columns.tolist())


# FEATURE_COLUMNS = ['LULC', 'drainage_density', 'geomorphology', 'Soil', 'Slope', 'Raninfall', 'Lithology', 'lineament_density']
# TARGET_COLUMN = 'validation point raw data'

# X = df[FEATURE_COLUMNS].values
# y = df[TARGET_COLUMN].values

# # # Mapping: x0 -> 'Soil', x1 -> 'Slope', etc.
# symbolic_variable_map = {f'x{i}': FEATURE_COLUMNS[i] for i in range(len(FEATURE_COLUMNS))}

# print("Symbolic Variable Mapping:")
# for symbol, name in symbolic_variable_map.items():
#      print(f"{symbol} → {name}")

def clamp(v, lo, hi):
    return max(lo, min(hi, v))

def safe_exp(x):
    # Prevent overflow
    return math.exp(clamp(x, -20, 20))

def safe_pow(x, y):
    # Prevent extreme exponents and huge bases
    base = abs(x) + 1e-6
    expn = clamp(y, -3, 3)
    return math.pow(base, expn)

# Protected division to avoid divide-by-zero
def protected_div(x, y):
    try:
        return x / y if abs(y) > 1e-6 else 1.0
    except:
        return 1.0

OPERATORS = {
    '+': (operator.add, 2),
    '-': (operator.sub, 2),
    '*': (operator.mul, 2),
    '/': (protected_div, 2),
    'neg': (lambda x: -x, 1),
    'sin': (math.sin, 1),
    'cos': (math.cos, 1),
    #'exp': (math.exp, 1),
    'log': (lambda x: math.log(abs(x) + 1e-6), 1),  # protected log
    'square': (lambda x: x * x, 1),
    'cube': (lambda x: x * x * x, 1),
    'exp': (safe_exp, 1),
    'pow': (safe_pow, 2),
}

class Node:
    def __init__(self, name, children=None):
        self.name = name
        self.children = children if children else []

    def copy(self):
        return Node(self.name, [child.copy() for child in self.children]) if self.children else Node(self.name)


    def evaluate(self, X_row, feature_map=None):
        if self.name in OPERATORS:
            func, arity = OPERATORS[self.name]
            if len(self.children) != arity:
                raise ValueError(f"Invalid expression: Operator '{self.name}' expects {arity} children, got {len(self.children)}")
            args = [child.evaluate(X_row, feature_map) for child in self.children]
            return func(*args)
        elif feature_map and self.name in feature_map:
            return X_row[feature_map[self.name]]
        elif isinstance(self.name, str) and self.name.startswith('x'):
            idx = int(self.name[1:])
            return X_row[idx]
        else:
            return float(self.name)

    # def count_nodes(self):
    #     return 1 + sum(child.count_nodes() for child in self.children)

    def to_string(self, feature_names=None):
        if self.name in OPERATORS:
            return f"{self.name}({', '.join(child.to_string(feature_names) for child in self.children)})"
        elif isinstance(self.name, str) and self.name.startswith('x') and feature_names:
            idx = int(self.name[1:])
            return feature_names[idx]
        else:
            return str(self.name)

    def __str__(self):
        return self.to_string()

    def weighted_complexity(self, parent_is_nonlinear=False, depth=1):
        LINEAR_OPS = {'+', '-', 'neg'}
        MILD_NONLINEAR_OPS = {'*'}
        STRONG_NONLINEAR_OPS = {'/', 'log', 'exp', 'pow', 'sin', 'cos', 'square', 'cube'}

#feature=0, +,=,neg=1, *=1.25, /,sin,cos,log,exp,square,cube=1.5, pow=2, constant=0.5
        if isinstance(self.name, str) and self.name.startswith('x'):
            cost = 0
            is_nonlinear = False
        elif self.name in LINEAR_OPS:
            cost = 1
            is_nonlinear = False
        elif self.name in MILD_NONLINEAR_OPS:
            cost = 1.25
            is_nonlinear = False
        elif self.name in STRONG_NONLINEAR_OPS:
            if self.name == '/':
                cost = 1.5
            elif self.name in ['square', 'cube']:
                cost = 1.5 if self.name == 'square' else 2
            elif self.name in ['sin', 'cos', 'log', 'exp']:
                cost = 1.25
            else:  # pow
                cost = 2
            is_nonlinear = True
        elif is_constant(self.name):
            cost = 0.5
            is_nonlinear = False
        else:
            cost = 1
            is_nonlinear = False

        # 2. Penalize ONLY problematic cases:
        # Very deep trees (>15 levels)
        depth_penalty = 0.1 * max(0, depth - 15)  # Applies to ALL nodes

        # Redundant nesting (sin(cos)), but not single nonlinear terms
        recursive_penalty = 0.05 if (parent_is_nonlinear and self.name in STRONG_NONLINEAR_OPS) else 0

        total = cost + depth_penalty + recursive_penalty
        for child in self.children:
            total += child.weighted_complexity(self.name in STRONG_NONLINEAR_OPS, depth + 1)
        return total

def is_constant(name):
    #Check if node is a numeric constant (handles negatives and floats)
    if isinstance(name, (int, float)):
        return True
    try:
        float(name)
        return True
    except (ValueError, TypeError):
        return False


# # Function to evaluate a tree
# def get_r2_and_complexity(tree, X, y):
#     try:
#         y_pred = np.array([tree.evaluate(row) for row in X])
#         r2 = r2_score(y, y_pred)
#     except Exception:
#         r2 = -np.inf
#     complexity = tree.count_nodes()
#     return r2, complexity

def to_readable_string(self, var_map):
    if self.name in OPERATORS:
        return f"{self.name}({', '.join(child.to_readable_string(var_map) for child in self.children)})"
    else:
        return var_map.get(self.name, str(self.name))


# Attach to Node class
Node.to_readable_string = to_readable_string

###*** LINEAR REGRESSION **###

from sklearn.linear_model import LinearRegression

def build_linear_model_tree(intercept: float, coefs: np.ndarray) -> 'Node':
    """
    Convert: y = intercept + sum_i coefs[i] * x_i
    into a Node tree.
    """
    # start with intercept as constant node
    # We use 'Node' here - make sure your Node class exists!
    expr = Node(str(float(intercept)))

    for i, c in enumerate(coefs):
        # Creates (Weight * x0), (Weight * x1), etc.
        term = Node('*', [Node(str(float(c))), Node(f'x{i}')])
        expr = Node('+', [expr, term])  # Adds it to the total

    return expr


def linear_regression_to_txt(
    X: np.ndarray,
    y: np.ndarray,
    feature_names: list,
    out_txt_path: str,
    var_map: dict,
    precision: int = 6
):
    # 1. Create and train the model
    model = LinearRegression(fit_intercept=True)
    model.fit(X, y)

    # 2. See how accurate it is
    y_pred = model.predict(X)
    r2 = r2_score(y, y_pred)

    # 3. Build the math tree to calculate "complexity"
    tree = build_linear_model_tree(model.intercept_, model.coef_)
    complexity = tree.weighted_complexity()

    # 4. Turn the tree into a human-readable sentence
    eq_str = tree.to_readable_string(var_map)

    # 5. Create the text report
    report = []
    report.append("Linear Regression")
    report.append(f"Features ({len(feature_names)}): {feature_names}")
    report.append("")
    report.append("Expression:")
    report.append(eq_str)
    report.append("")
    report.append(f"R2: {r2:.{precision}f}")
    report.append(f"Weighted complexity: {complexity:.{precision}f}")

    report_text = "\n".join(report)

    # 6. Print to screen and save to file
    print(report_text)
    with open(out_txt_path, "w", encoding="utf-8") as f:
        f.write(report_text + "\n")

    return {
        "r2": float(r2),
        "weighted_complexity": float(complexity),
        "tree": tree,
        "intercept": float(model.intercept_),
        "coef": model.coef_.astype(float),
        "txt_path": out_txt_path,
    }

linear_txt_path = "/content/drive/My Drive/GWL/r2_complexity/train219_val99_1obj_r2 of GP/linear_regression.txt"

lin_result = linear_regression_to_txt(
    X=X,
    y=y,
    feature_names=FEATURE_COLUMNS,
    out_txt_path=linear_txt_path,
    var_map=symbolic_variable_map,
    precision=6
)

def generate_random_tree(max_depth, feature_count, current_depth=0, parent_op=None):
    # Make deeper trees more likely
    terminal_prob = 0.1 + 0.4 * (current_depth / max_depth) ## (more terminals → smaller trees)

    if current_depth >= max_depth or random.random() < terminal_prob:
        # Prefer features (70%) over constants (30%)
        if random.random() < 0.7:
            return Node(f'x{random.randint(0, feature_count - 1)}')
        else:
            return Node(str(round(random.uniform(-5, 5), 2)))
    else:
        # Add operator variety
        op_weights = {
            '+': 0.18, '-': 0.18, '*': 0.20, '/': 0.07,
            'sin': 0.06, 'cos': 0.06,
            'log': 0.06, 'exp': 0.04,
            'square': 0.06, 'cube': 0.03,
            'pow': 0.06
        }

        # # Avoid recursive nonlinearity
        # if parent_op in {'log', 'exp', 'pow', 'sin', 'cos', 'square', 'cube'}:
        #     for op in ['log', 'exp', 'pow', 'sin', 'cos', 'square', 'cube']:
        #         op_weights.pop(op, None)

        op = random.choices(list(op_weights.keys()), weights=list(op_weights.values()), k=1)[0]
        func, arity = OPERATORS[op]
        children = [generate_random_tree(max_depth, feature_count, current_depth + 1, op) for _ in range(arity)]
        return Node(op, children)

# Recursively collect all nodes along with their parent nodes
def collect_nodes_with_parents(node, parent=None):
    nodes = [(node, parent)]
    for child in node.children:
        nodes.extend(collect_nodes_with_parents(child, node))
    return nodes

## Crossover
def crossover(tree1, tree2):
    child1 = copy.deepcopy(tree1)
    child2 = copy.deepcopy(tree2)

    # Collect all nodes with their parent references
    nodes1 = collect_nodes_with_parents(child1)
    nodes2 = collect_nodes_with_parents(child2)

    # Prefer internal nodes (i.e., operators), fallback to any node
    op_nodes1 = [n for n in nodes1 if n[0].name in OPERATORS]
    op_nodes2 = [n for n in nodes2 if n[0].name in OPERATORS]

    if op_nodes1 and op_nodes2:
        (target1, parent1), (target2, parent2) = random.choice(op_nodes1), random.choice(op_nodes2)
    else:
        (target1, parent1), (target2, parent2) = random.choice(nodes1), random.choice(nodes2)

    # Swap the subtrees
    if parent1 is None:
        child1 = target2
    else:
        idx = parent1.children.index(target1)
        parent1.children[idx] = target2

    if parent2 is None:
        child2 = target1
    else:
        idx = parent2.children.index(target2)
        parent2.children[idx] = target1

    # print crossover to check
    # print(f"[CROSSOVER] Parent1: {tree1.to_string()}")
    # print(f"[CROSSOVER] Parent2: {tree2.to_string()}")
    # print(f"[CROSSOVER] Child1 : {child1.to_string()}")
    # print(f"[CROSSOVER] Child2 : {child2.to_string()}")

    return child1, child2


# # # Mutation
def mutate(tree, max_depth, feature_count):
    #tree_copy = copy.deepcopy(tree)
    tree_copy = tree.copy()  # assuming you have a custom .copy() method
    nodes = collect_nodes_with_parents(tree_copy)
    target_node, parent = random.choice(nodes)

    mutation_type = random.choice(['subtree', 'operator', 'constant', 'feature'])

    if mutation_type == 'subtree':
        new_subtree = generate_random_tree(max_depth=max_depth, feature_count=feature_count)
        if parent is None:
            return new_subtree
        else:
            idx = parent.children.index(target_node)
            parent.children[idx] = new_subtree

    elif mutation_type == 'operator' and target_node.name in OPERATORS:
        current_op = target_node.name
        valid_ops = [op for op in OPERATORS if OPERATORS[op][1] == OPERATORS[current_op][1] and op != current_op]
        if valid_ops:
            new_op = random.choice(valid_ops)
            target_node.name = new_op

    elif mutation_type == 'constant' and is_constant(target_node.name):
        new_val = round(random.uniform(-10, 10), 2)
        target_node.name = new_val

    elif mutation_type == 'feature' and isinstance(target_node.name, str) and target_node.name.startswith('x'):
        old_feature = target_node.name
        new_feature = old_feature
        while new_feature == old_feature:
            new_feature = f'x{random.randint(0, feature_count - 1)}'
        target_node.name = new_feature
        #print(f"[MUTATION] Replaced feature {old_feature} → {new_feature}")

    return tree_copy

class Individual:
    def __init__(self, tree, X, y, feature_names, validation_labels=None):
        self.tree = tree
        self.X = X
        self.y = y
        self.feature_names = feature_names
        self.validation_labels = validation_labels

        self.rank = None
        self.crowding_distance = 0.0

        self._evaluate()
        #print(f"[Debug] Feature names: {self.feature_names}")


    def _evaluate(self):
        try:
            # Evaluate predictions
            y_pred = np.clip([self.tree.evaluate(row) for row in self.X], -1e3, 1e3)
            self.r2 = r2_score(self.y, y_pred)
            self.predicted = y_pred
        except Exception:
            self.r2 = -np.inf
            self.predicted = [None] * len(self.y)

        # complexity calculation
        #self.complexity = self.tree.count_nodes()
        self.complexity = self.tree.weighted_complexity()



    @property
    def fitness(self):
        return -self.r2  # minimize negative R² (maximize R²)

    @property
    def symbolic(self):
        return str(self.tree)

    @property
    def readable(self):
        return self.tree.to_readable_string(self.feature_names)


    def copy(self):
        return Individual(copy.deepcopy(self.tree), self.X, self.y, self.feature_names, self.validation_labels)

    # def score(self, alpha=1.0, beta=0.01):
    #     return alpha * self.r2 - beta * self.complexity

# NSGA-II survivor selection using non-dominated sorting and crowding distance

def objective_value(ind, obj):
    if obj == 'r2':
        return -ind.r2   # convert R² to minimization
    elif obj == 'complexity':
        return ind.complexity
    else:
        return getattr(ind, obj)


def compute_crowding_distance(front, objectives):
    size = len(front)
    if size == 0:
        return {}

    distance = {ind: 0.0 for ind in front}

    for obj in objectives:
        sorted_front = sorted(front, key=lambda ind: objective_value(ind, obj))

        distance[sorted_front[0]] = float('inf')
        distance[sorted_front[-1]] = float('inf')

        obj_min = objective_value(sorted_front[0], obj)
        obj_max = objective_value(sorted_front[-1], obj)

        if obj_max == obj_min:
            continue

        for j in range(1, size - 1):
            prev_val = objective_value(sorted_front[j - 1], obj)
            next_val = objective_value(sorted_front[j + 1], obj)

            distance[sorted_front[j]] += (next_val - prev_val) / (obj_max - obj_min)

    return distance



def select_survivors(population, num_survivors):
    # Sort population by R² descending
    return sorted(population, key=lambda ind: ind.r2, reverse=True)[:num_survivors]


def tournament_selection_r2(population, k, tournament_size=2):
    ## Single-objective tournament selection based only on R².

    selected = []
    for _ in range(k):
        contenders = random.sample(population, tournament_size)
        winner = max(contenders, key=lambda ind: ind.r2)
        selected.append(winner)
    return selected

def generate_offspring(parents, num_offspring, max_depth, feature_count, mutation_rate=0.3):
    offspring = []
    while len(offspring) < num_offspring:
        p1, p2 = random.sample(parents, 2)

        # Crossover
        child1_tree, child2_tree = crossover(p1.tree, p2.tree)
        print(f"[CROSSOVER] Parent1: {p1.tree.to_string()}")
        print(f"[CROSSOVER] Parent2: {p2.tree.to_string()}")
        print(f"[CROSSOVER] Child1 : {child1_tree.to_string()}")
        print(f"[CROSSOVER] Child2 : {child2_tree.to_string()}")

        child1 = Individual(child1_tree, p1.X, p1.y, p1.feature_names)
        child2 = Individual(child2_tree, p2.X, p2.y, p2.feature_names)

        # Mutation for Child1
        if random.random() < mutation_rate:
            if random.random() < 0.05: # only 5% chance of full reset
                new_tree = generate_random_tree(max_depth, feature_count)
                print(f"[MUTATION] Child1 replaced by new random tree: {new_tree.to_string()}")
                child1 = Individual(new_tree, p1.X, p1.y, p1.feature_names)
            else:
                print(f"[MUTATION] Before mutation (Child1): {child1.tree.to_string()}")
                mutated_tree = mutate(child1.tree, max_depth, feature_count)
                print(f"[MUTATION] After mutation  (Child1): {mutated_tree.to_string()}")
                child1 = Individual(mutated_tree, p1.X, p1.y, p1.feature_names)

        # Mutation for Child2
        if random.random() < mutation_rate:
            if random.random() < 0.05:  # only 5% chance of full reset
                new_tree = generate_random_tree(max_depth, feature_count)
                print(f"[MUTATION] Child2 replaced by new random tree: {new_tree.to_string()}")
                child2 = Individual(new_tree, p2.X, p2.y, p2.feature_names)
            else:
                print(f"[MUTATION] Before mutation (Child2): {child2.tree.to_string()}")
                mutated_tree = mutate(child2.tree, max_depth, feature_count)
                print(f"[MUTATION] After mutation  (Child2): {mutated_tree.to_string()}")
                child2 = Individual(mutated_tree, p2.X, p2.y, p2.feature_names)

        offspring.append(child1)
        if len(offspring) < num_offspring:
            offspring.append(child2)

    return offspring[:num_offspring]

## pareto front method


###TEST #####.   feature track per generation
from collections import Counter

feature_usage_log = []  # Global tracker


def count_features(tree):
    if isinstance(tree.name, str) and tree.name.startswith('x'):
        return Counter([tree.name])
    counts = Counter()
    for child in tree.children:
        counts += count_features(child)
    return counts

all_logs = []

def create_individual_population(n_individuals, max_depth, feature_count, X, y, feature_names):
    population = []
    for _ in range(n_individuals):
        tree = generate_random_tree(max_depth=max_depth, feature_count=feature_count)
        ind = Individual(tree, X, y, feature_names)
        population.append(ind)
    return population

#all_logs = []

def run_gp_evolution(
    X, y, feature_names,
    population_size=100,
    generations=100,
    max_depth=6,
    mutation_rate=.3
):
    # Initial population
    population = create_individual_population(
        n_individuals=population_size,
        max_depth=max_depth,
        feature_count=len(feature_names),
        X=X,
        y=y,
        feature_names=feature_names
    )

    gen_expr_log_path = '/content/drive/My Drive/GWL/r2_complexity/train219_val99_1obj_r2 of GP/train219_all_generation_expressions_log.txt'
    gen_expr_log = open(gen_expr_log_path, 'w')

    best_overall = None

    for gen in range(generations):

        parents = tournament_selection_r2(
            population,
            k=population_size,
            tournament_size=2
        )

        offspring = generate_offspring(
            parents=parents,
            num_offspring=population_size,
            max_depth=max_depth,
            feature_count=len(feature_names),
            mutation_rate=mutation_rate
        )

        combined_population = population + offspring

        population = sorted(
            combined_population,
            key=lambda ind: ind.r2,
            reverse=True
        )[:population_size]

        gen_best = max(population, key=lambda ind: ind.r2)

        if best_overall is None or gen_best.r2 > best_overall.r2:
            best_overall = gen_best

        gen_header = f"\nGeneration {gen + 1}"
        print(gen_header)
        gen_expr_log.write(gen_header + '\n')

        for i, ind in enumerate(population):
            expr_line = f"Individual {i + 1}, R²: {ind.r2:.4f}, Complexity: {ind.complexity:.4f}, Expr: {ind.readable}"
            print(expr_line)
            gen_expr_log.write(expr_line + '\n')

        generation_usage = Counter()
        for ind in population:
            generation_usage += count_features(ind.tree)
        feature_usage_log.append(generation_usage)

        for i, ind in enumerate(population):
            try:
                y_pred = [ind.tree.evaluate(row) for row in ind.X]
            except Exception:
                y_pred = [None] * len(ind.y)

            target_str = ",".join([f"{v:.4f}" for v in ind.y])
            pred_str = ",".join([f"{v:.4f}" if v is not None else "NaN" for v in y_pred])

            all_logs.append({
                "Generation": gen + 1,
                "Individual": i,
                "R2": ind.r2,
                "Complexity": ind.complexity,
                "Targets": target_str,
                "Predictions": pred_str,
            })

    gen_expr_log.close()
    return population, best_overall

## GP Run ---- Single run
#_________________________________________

# final_pop, best_overall = run_gp_evolution(
#     X=X,
#     y=y,
#     feature_names=symbolic_variable_map,
#     population_size=100,
#     generations=100,
#     max_depth=6,           # 4
#     mutation_rate=0.3      # 0.7/0.3
# )


# log_df = pd.DataFrame(all_logs)
# log_df.to_excel("/content/drive/My Drive/GWL/r2_complexity/train219_val99_1obj_r2 of GP/train219_1obj_full_run_log.xlsx", index=False)

# ## best r2 from all generation

# print("\nBest Individual Across All Generations")
# print(f"R²: {best_overall.r2:.4f}, Complexity: {best_overall.complexity:.4f}, Expr: {best_overall.readable}")

#########

# =========================
# MULTI-RUN WITH BEST EXPRESSION FROM ALL -20 RUNS
# =========================

import os, random
import numpy as np

import sys
sys.setrecursionlimit(200000)

NUM_RUNS = 20  ##20
BASE_SEED = 42
SEEDS = [BASE_SEED + i for i in range(NUM_RUNS)]

OUT_DIR = "/content/drive/My Drive/GWL/r2_complexity/train219_val99_1obj_r2 of GP"
os.makedirs(OUT_DIR, exist_ok=True)

ALL_RUNS_BEST_TXT = os.path.join(OUT_DIR, "single_obj_r2_best_per_run.txt")

# clear file once
with open(ALL_RUNS_BEST_TXT, "w") as f:
    f.write("SINGLE-OBJECTIVE GP (maximize R²)\n")
    f.write("="*70 + "\n\n")

best_per_run = []   # store best_overall from each run

for run_idx, seed in enumerate(SEEDS, start=1):
    print(f"\n\n**RUN {run_idx}/{NUM_RUNS}")


    random.seed(seed)
    np.random.seed(seed)

    # Run one GP evolution
    # Run one GP evolution (SAFE)
    try:
        final_pop, best_overall = run_gp_evolution(
            X=X,
            y=y,
            feature_names=symbolic_variable_map,
            population_size=100,
            generations=100,
            max_depth=6,
            mutation_rate=0.3
        )
    except RecursionError as e:
        msg = f"Run {run_idx:02d} | RecursionError inside GP | seed={seed} | {e}"
        print(msg)
        with open(ALL_RUNS_BEST_TXT, "a") as f:
            f.write(msg + "\n")
        continue

    best_per_run.append(best_overall)

    # Safe readable (readable can also trigger recursion)
    try:
        readable_expr = best_overall.readable
    except RecursionError:
        readable_expr = "<RecursionError while building readable expression>"

    line = (
        f"\nRun {run_idx:02d} | "
        f"Best R2: {best_overall.r2:.6f} | "
        f"Complexity: {best_overall.complexity:.6f} | "
        f"Expr: {readable_expr}"
    )
    print(line)

    # ---- append to single txt ----
    with open(ALL_RUNS_BEST_TXT, "a") as f:
        f.write(line + "\n")


    # ======================================================
    # SAVE BEST RESULT FOUND SO FAR AFTER EVERY COMPLETED RUN
    # ======================================================
    BEST_SO_FAR_TXT = os.path.join(
        OUT_DIR,
        "single_obj_best_so_far.txt"
    )

    best_so_far = max(best_per_run, key=lambda ind: ind.r2)

    try:
        best_so_far_expr = best_so_far.readable
    except RecursionError:
        best_so_far_expr = "<RecursionError while building readable expression>"

    with open(BEST_SO_FAR_TXT, "w", encoding="utf-8") as f:
        f.write("BEST SINGLE-OBJECTIVE RESULT FOUND SO FAR\n")
        f.write("=" * 60 + "\n\n")
        f.write(f"Successful runs: {len(best_per_run)}\n")
        f.write(f"Latest completed run: {run_idx}\n")
        f.write(f"R2: {best_so_far.r2:.6f}\n")
        f.write(f"Complexity: {best_so_far.complexity:.6f}\n")
        f.write(f"Expression: {best_so_far_expr}\n")


# ---- best across all runs ----
print("\n\n **BEST ACROSS ALL RUNS**")

if not best_per_run:
    print("No successful runs (all failed due to RecursionError).")
else:
    best_across_runs = max(best_per_run, key=lambda ind: ind.r2)

    # Safe readable (important!)
    try:
        readable_expr = best_across_runs.readable
    except RecursionError:
        readable_expr = "<RecursionError while building readable expression>"

    print(
        f"Best R2: {best_across_runs.r2:.6f} | "
        f"Complexity: {best_across_runs.complexity:.6f} | "
        f"Expr: {readable_expr}"
    )

    with open(ALL_RUNS_BEST_TXT, "a") as f:
        f.write("\n\n**BEST ACROSS ALL RUNS**\n")
        f.write(
            f"Best R2: {best_across_runs.r2:.6f} | "
            f"Complexity: {best_across_runs.complexity:.6f} | "
            f"Expr: {readable_expr}\n"
        )

print("\nSaved:", ALL_RUNS_BEST_TXT)

from google.colab import drive
drive.mount("/content/drive")

# MULTI RUN -20 RUNS

# ==========================================================
# VALIDATE BEST SINGLE-OBJECTIVE EXPRESSION FROM 20 RUNS
# ==========================================================

import re
import pandas as pd
import numpy as np
from sklearn.metrics import r2_score, mean_squared_error, mean_absolute_error

# ----------------------------------------------------------
# 1. FILE PATHS
# ----------------------------------------------------------

# result_file = (
#     "/content/drive/My Drive/GWL/r2_complexity/"
#     "train219_val99_1obj_r2 of GP/single_obj_r2_best_per_run.txt"
# )

result_file = (
    "/content/drive/My Drive/GWL/r2_complexity/"
    "train219_val99_1obj_r2 of GP/single_obj_best_so_far.txt"
)

validation_path = (
    "/content/drive/My Drive/GWL/r2_complexity/"
    "train219_val99_1obj_r2 of GP/validation_test99_dataset.csv"
)

# ----------------------------------------------------------
# 2. LOAD BEST RESULT FOUND SO FAR
# ----------------------------------------------------------

best_r2 = None
best_complexity = None
best_prefix = None

with open(result_file, "r", encoding="utf-8") as f:
    for line in f:

        line = line.strip()

        if line.startswith("R2:"):
            best_r2 = float(line.split(":", 1)[1].strip())

        elif line.startswith("Complexity:"):
            best_complexity = float(
                line.split(":", 1)[1].strip()
            )

        elif line.startswith("Expression:"):
            best_prefix = line.split(":", 1)[1].strip()


if best_r2 is None:
    raise ValueError("Could not find R2 in the result file.")

if best_complexity is None:
    raise ValueError("Could not find complexity in the result file.")

if best_prefix is None:
    raise ValueError("Could not find expression in the result file.")


print("Best result found so far loaded successfully.")
print("Training R2 :", best_r2)
print("Complexity  :", best_complexity)


# ----------------------------------------------------------
# 3. CORRECTED PREFIX PARSER
#    Protects feature names that contain spaces
# ----------------------------------------------------------

def parse_prefix(expr_str):

    # Protect multi-word feature names before tokenization
    replacements = {
        "Lineament density": "Lineament_density",
        "Drainage density": "Drainage_density"
    }

    for old, new in replacements.items():
        expr_str = expr_str.replace(old, new)

    tokens = (
        expr_str
        .replace('(', ' ( ')
        .replace(')', ' ) ')
        .replace(',', ' ')
        .split()
    )

    def parse_tokens(tokens):

        if not tokens:
            return None

        token = tokens.pop(0)

        # Restore original feature names
        if token == "Lineament_density":
            token = "Lineament density"

        elif token == "Drainage_density":
            token = "Drainage density"

        if token in OPERATORS:

            func, arity = OPERATORS[token]

            children = [
                parse_tokens(tokens)
                for _ in range(arity)
            ]

            return Node(token, children)

        elif token not in ['(', ')']:

            return Node(token)

        else:

            return parse_tokens(tokens)

    return parse_tokens(tokens)


# ----------------------------------------------------------
# 4. RECONSTRUCT THE WINNING EXPRESSION TREE
# ----------------------------------------------------------

best_tree = parse_prefix(best_prefix)

print("Expression tree reconstructed successfully.")
print("Tree root:", best_tree.name)

# ----------------------------------------------------------
# 5. LOAD VALIDATION DATA
# ----------------------------------------------------------

FEATURE_COLUMNS = [
    'Soil',
    'Slope',
    'Rain',
    'LULC',
    'Lithology',
    'Lineament density',
    'Geomorphology',
    'Drainage density'
]

TARGET_COLUMN = 'Net Groundwater Recharge'

df_val = pd.read_csv(validation_path)

X_val = df_val[FEATURE_COLUMNS].values
y_val = df_val[TARGET_COLUMN].values

feature_map = {
    name: idx
    for idx, name in enumerate(FEATURE_COLUMNS)
}

print("Validation samples:", len(df_val))

# ----------------------------------------------------------
# 6. EVALUATE THE WINNING EXPRESSION
# ----------------------------------------------------------

preds = []

for row in X_val:

    pred = best_tree.evaluate(
        row,
        feature_map
    )

    preds.append(pred)

preds = np.array(preds, dtype=float)

# Check for invalid values
if np.any(np.isnan(preds)):
    print("Warning: NaN values found in predictions.")

if np.any(np.isinf(preds)):
    print("Warning: Infinite values found in predictions.")

# ----------------------------------------------------------
# 7. CALCULATE VALIDATION METRICS
# ----------------------------------------------------------

validation_r2 = r2_score(
    y_val,
    preds
)

mse_val = mean_squared_error(
    y_val,
    preds
)

rmse_val = np.sqrt(
    mse_val
)

mae_val = mean_absolute_error(
    y_val,
    preds
)

# ----------------------------------------------------------
# 8. PRINT RESULTS
# ----------------------------------------------------------

print("\n===== SINGLE-OBJECTIVE VALIDATION RESULT =====")

print(f"Training R2   : {best_r2:.6f}")
print(f"Validation R2 : {validation_r2:.6f}")
print(f"Complexity    : {best_complexity:.6f}")
print(f"MSE           : {mse_val:.6f}")
print(f"RMSE          : {rmse_val:.6f}")
print(f"MAE           : {mae_val:.6f}")


# ----------------------------------------------------------
# 9. SAVE VALIDATION RESULT TO TXT FILE
# ----------------------------------------------------------

output_txt = (
    "/content/drive/My Drive/GWL/r2_complexity/"
    "train219_val99_1obj_r2 of GP/"
    "single_obj_validation_r2.txt"
)

with open(output_txt, "w", encoding="utf-8") as f:

    f.write("SINGLE-OBJECTIVE SYMBOLIC REGRESSION VALIDATION RESULT\n")
    f.write("=" * 60 + "\n\n")

    f.write(f"Training R2   : {best_r2:.6f}\n")
    f.write(f"Validation R2 : {validation_r2:.6f}\n")
    f.write(f"Complexity    : {best_complexity:.6f}\n")
    f.write(f"MSE           : {mse_val:.6f}\n")
    f.write(f"RMSE          : {rmse_val:.6f}\n")
    f.write(f"MAE           : {mae_val:.6f}\n")

    f.write("\nPrefix Expression:\n")
    f.write(best_prefix + "\n")

print("\nValidation result saved to:")
print(output_txt)

# MULTI RUN -20 RUNS

#==========================================================
# SAVE SINGLE-OBJECTIVE VALIDATION DETAILS TO EXCEL
# ==========================================================

import os
import pandas as pd

excel_path = (
    "/content/drive/My Drive/GWL/r2_complexity/"
    "train219_val99_1obj_r2 of GP/"
    "single_obj_validation_results.xlsx"
)

os.makedirs(os.path.dirname(excel_path), exist_ok=True)

# ----------------------------------------------------------
# Prepare validation data
# ----------------------------------------------------------

df_result = df_val[FEATURE_COLUMNS].copy()

df_result["Actual"] = y_val
df_result["Predicted"] = preds

# ----------------------------------------------------------
# Save to Excel
# ----------------------------------------------------------

with pd.ExcelWriter(excel_path, engine="openpyxl") as writer:

    # Write validation observations starting from row 3
    df_result.to_excel(
        writer,
        sheet_name="Best_Expression",
        index=False,
        startrow=2
    )

    # Access worksheet
    ws = writer.sheets["Best_Expression"]

    # First row: main result information
    ws["A1"] = (
        f"Training R²: {best_r2:.6f}, "
        f"Validation R²: {validation_r2:.6f}, "
        f"Complexity: {best_complexity:.6f}, "
        f"MSE: {mse_val:.6f}, "
        f"RMSE: {rmse_val:.6f}, "
        f"MAE: {mae_val:.6f}, "
        f"Expression: {best_prefix}"
    )

print("\nExcel file saved to:")
print(excel_path)

from google.colab import drive
drive.mount("/content/drive")

# MULTI RUN -20 RUNS

## prefix to infix

import re

#input_file = "/content/drive/MyDrive/GWL/r2_complexity/train219_val99_1obj_r2 of GP/single_obj_r2_best_per_run.txt"
input_file = "/content/drive/MyDrive/GWL/r2_complexity/train219_val99_1obj_r2 of GP/single_obj_best_so_far.txt"
output_txt = "/content/drive/MyDrive/GWL/r2_complexity/train219_val99_1obj_r2 of GP/single_obj_best_infix.txt"

def split_args(s: str):
    args, depth, start = [], 0, 0
    for i, ch in enumerate(s):
        if ch == '(':
            depth += 1
        elif ch == ')':
            depth -= 1
        elif ch == ',' and depth == 0:
            args.append(s[start:i].strip())
            start = i + 1
    args.append(s[start:].strip())
    return args

def prefix_to_infix(expr: str) -> str:
    expr = expr.strip()

    # number
    if re.fullmatch(r"-?\d+(\.\d+)?", expr):
        return expr

    # variable name (underscore ok)
    if re.fullmatch(r"[A-Za-z_][A-Za-z0-9_]*", expr):
        return expr

    # general call name(...)
    m = re.match(r"^([A-Za-z_+\-*/][A-Za-z0-9_]*)\((.*)\)$", expr)
    if not m:
        return expr

    name = m.group(1)
    inside = m.group(2).strip()
    args = split_args(inside)
    args_infix = [prefix_to_infix(a) for a in args]

    # binary ops
    if name in {"+", "-", "*", "/"} and len(args_infix) == 2:
        a, b = args_infix
        return f"({a} {name} {b})"

    # power
    if name == "pow" and len(args_infix) == 2:
        a, b = args_infix
        return f"({a} ^ {b})"

    # unary neg (if your GP uses neg(x))
    if name == "neg" and len(args_infix) == 1:
        return f"(-{args_infix[0]})"

    # other functions: cos(x), square(x), cube(x), exp(x), ...
    return f"{name}({', '.join(args_infix)})"

# -----------------------------
# READ BEST RESULT FOUND SO FAR
# -----------------------------
best_r2 = None
best_complexity = None
best_prefix = None

with open(input_file, "r", encoding="utf-8") as f:
    for line in f:

        line = line.strip()

        if line.startswith("R2:"):
            best_r2 = line.split(":", 1)[1].strip()

        elif line.startswith("Complexity:"):
            best_complexity = line.split(":", 1)[1].strip()

        elif line.startswith("Expression:"):
            best_prefix = line.split(":", 1)[1].strip()


if best_r2 is None:
    raise ValueError("Could not find R2 in the result file.")

if best_complexity is None:
    raise ValueError("Could not find complexity in the result file.")

if best_prefix is None:
    raise ValueError("Could not find expression in the result file.")


best_infix = prefix_to_infix(best_prefix)

# Print to console
print("===== BEST SINGLE-OBJECTIVE RESULT FOUND SO FAR =====")
print("R2        :", best_r2)
print("Complexity:", best_complexity)

print("\nPrefix:\n", best_prefix)
print("\nInfix:\n", best_infix)


# Save to TXT
with open(output_txt, "w", encoding="utf-8") as f:

    f.write("BEST SINGLE-OBJECTIVE RESULT FOUND SO FAR\n")
    f.write("=" * 60 + "\n\n")

    f.write(f"R2: {best_r2}\n")
    f.write(f"Complexity: {best_complexity}\n\n")

    f.write("Prefix Expression:\n")
    f.write(best_prefix + "\n\n")

    f.write("Infix Expression:\n")
    f.write(best_infix + "\n")


print("\nSaved TXT to:", output_txt)

# ==========================================================
# SAVE SINGLE-OBJECTIVE BEST EXPRESSION AS LATEX TABLE
# Includes Solution column
# ==========================================================

output_tex = (
    "/content/drive/MyDrive/GWL/r2_complexity/"
    "train219_val99_1obj_r2 of GP/"
    "single_obj_best_latex.tex"
)

def infix_to_latex(expr):
    """Convert infix expression to LaTeX format."""

    expr = expr.replace('&', r'\&')
    expr = expr.replace('%', r'\%')
    expr = expr.replace('_', r'\_')

    expr = expr.replace('sin(', r'\sin(')
    expr = expr.replace('cos(', r'\cos(')
    expr = expr.replace('log(', r'\log(')
    expr = expr.replace('exp(', r'\exp(')

    # Keep multiplication as *
    expr = expr.replace('*', r' * ')

    return expr


latex_expr = infix_to_latex(best_infix)

r2_formatted = f"{float(best_r2):.6f}"
complexity_formatted = f"{float(best_complexity):.2f}"

with open(output_tex, "w", encoding="utf-8") as f:

    f.write(r"\begin{table}[h]" + "\n")
    f.write(r"\centering" + "\n")

    f.write(
        r"\caption{Highest-$R^2$ expression obtained from single-objective symbolic regression}"
        + "\n"
    )

    f.write(r"\label{tab:best_single_obj}" + "\n")

    f.write(r"\setlength{\tabcolsep}{4pt}" + "\n")
    f.write(r"\renewcommand{\arraystretch}{1.1}" + "\n")

    # Four columns:
    # Solution | R² | Complexity | Expression
    f.write(
        r"\begin{tabularx}{\textwidth}"
        r"{|c|c|c|>{\raggedright\arraybackslash}X|}"
        + "\n"
    )

    f.write(r"\hline" + "\n")

    f.write(
        r"Solution & R\textsuperscript{2} & Complexity & Expression \\"
        + "\n"
    )

    f.write(r"\hline" + "\n")

    f.write(
        f"1 & "
        f"{r2_formatted} & "
        f"{complexity_formatted} & "
        f"\\raggedright ${latex_expr}$ \\\\"
        + "\n"
    )

    f.write(r"\hline" + "\n")
    f.write(r"\end{tabularx}" + "\n")
    f.write(r"\end{table}" + "\n")

print("Saved:", output_tex)

##### Single Run ------- Old table version

# Save Single Objective BEST ACROSS ALL RUNS as a LaTeX table

output_tex = "/content/drive/MyDrive/GWL/r2_complexity/train219_val99_1obj_r2 of GP/single_obj_best_latex.tex"

with open(output_tex, "w", encoding="utf-8") as f:
    f.write("% Auto-generated: BEST ACROSS ALL RUNS\n")
    f.write("\\begin{table}[ht]\n")
    f.write("\\centering\n")
    f.write("\\caption{Best expression from single-objective symbolic regression}\n")
    f.write("\\label{tab:best_single_obj}\n")
    f.write("\\renewcommand{\\arraystretch}{1.15}\n")
    f.write("\\small\n")
    f.write("\\begin{tabular}{|c|c|p{12cm}|}\n")
    f.write("\\hline\n")
    f.write("$R^2$ & Complexity & Expression \\\\\n")
    f.write("\\hline\n")
    f.write(f"{best_r2} & {float(best_complexity):.2f} & \\texttt{{\\detokenize{{{best_infix}}}}} \\\\\n")
    f.write("\\hline\n")
    f.write("\\end{tabular}\n")
    f.write("\\end{table}\n")
print("Saved:", output_tex)



# print("Generations in all_logs:", sorted(set(entry["Generation"] for entry in all_logs)))
# print(len(all_logs))  # should be > 0
# print(all_logs[-1])   # show last log entry to confirm structure

# #plot r2 per genertation

import matplotlib.pyplot as plt

gen_list = []
r2_list = []

for entry in all_logs:
    generation = entry["Generation"]
    r2 = entry["R2"]
    if isinstance(r2, (int, float)):
        gen_list.append(generation)
        r2_list.append(r2)


plt.figure(figsize=(10, 5))
plt.scatter(gen_list, r2_list, alpha=0.5)
plt.xlabel("Generation")
plt.ylabel("R² Score")
plt.title("All R² Values Over Generations")
plt.grid(True)
plt.tight_layout()
plt.show()

### plot max r2 over generation

from collections import defaultdict
import pandas as pd
import matplotlib.pyplot as plt


r2_by_gen = defaultdict(list)
for entry in all_logs:
    if isinstance(entry["R2"], (int, float)) and not pd.isna(entry["R2"]):
        r2_by_gen[entry["Generation"]].append(entry["R2"])


#avg_r2_per_gen = {}
max_r2_per_gen = {}

for gen, vals in r2_by_gen.items():
    if vals:
        #avg_r2_per_gen[gen] = sum(vals) / len(vals)
        max_r2_per_gen[gen] = max(vals)


#avg_series = pd.Series(avg_r2_per_gen).sort_index()
max_series = pd.Series(max_r2_per_gen).sort_index()


plt.figure(figsize=(12, 5))
#plt.plot(avg_series.index, avg_series.values, label="Average R²", color='blue')
plt.plot(max_series.index, max_series.values, label="Max R²", color='green')
plt.xlabel("Generation", fontsize=12)
plt.ylabel("R²", fontsize=12)
plt.title("Max R²", fontsize=14)
plt.legend()
plt.grid(True, linestyle='--', linewidth=0.5)
plt.tight_layout()
plt.show()

# best individual by R² from final population
best_by_r2 = max(final_pop, key=lambda ind: ind.r2)

print("\nBest Individual by R²:")
print(f"R²: {best_by_r2.r2:.4f}, Complexity: {best_by_r2.complexity:.4f}, Expr: {best_by_r2.readable}")

best_r2_txt_path = "/content/drive/My Drive/GWL/r2_complexity/train219_val99_1obj_r2 of GP/best_r2_individual.txt"

with open(best_r2_txt_path, 'w') as f:
    f.write("Best Individual Across All Generations:\n")
    f.write(f"R²: {best_overall.r2:.4f}, Complexity: {best_overall.complexity:.4f}, Expr: {best_overall.readable}\n")
    #f.write(f"R²: {best_overall.r2:.4f}\n")
    #f.write(f"Complexity: {best_overall.complexity:.4f}\n")
    #f.write(f"Expression: {best_overall.readable}\n")

print(f"Best R² individual saved to: {best_r2_txt_path}")

import math

avg_r2_per_gen = {}
max_r2_per_gen = {}

for gen, vals in r2_by_gen.items():
    # filter out inf, -inf, NaN
    valid_r2s = [v for v in vals if isinstance(v, (int, float)) and math.isfinite(v)]
    if valid_r2s:
        avg_r2_per_gen[gen] = sum(valid_r2s) / len(valid_r2s)
        max_r2_per_gen[gen] = max(valid_r2s)

## plot max r2 and average r2 over generation

import matplotlib.pyplot as plt
import pandas as pd



avg_series = pd.Series(avg_r2_per_gen).sort_index()
max_series = pd.Series(max_r2_per_gen).sort_index()


plt.figure(figsize=(12, 5))

# Average R² line
plt.plot(avg_series.index, avg_series.values, label="Average R²", color='blue', linewidth=1.5)

# Max R² line with markers
plt.plot(max_series.index, max_series.values, label="Max R²", color='green', linestyle='--', linewidth=2.0, marker='o', markersize=3)

plt.xlabel("Generation", fontsize=12)
plt.ylabel("R²", fontsize=12)
plt.title("Average and Max R² Over Generations", fontsize=14)
plt.ylim(ymin, ymax)
plt.grid(True, linestyle='--', linewidth=0.5)
plt.legend()
plt.tight_layout()
plt.show()

##### TEST. Track features over generation. ###

import pandas as pd
import matplotlib.pyplot as plt

# Convert to DataFrame
usage_df = pd.DataFrame(feature_usage_log).fillna(0)

# Normalize per generation
usage_df_norm = usage_df.div(usage_df.sum(axis=1), axis=0)

# Plot
plt.figure(figsize=(12, 6))
for column in usage_df_norm.columns:
    plt.plot(usage_df_norm[column], label=column)

plt.xlabel("Generation")
plt.ylabel("Normalized Feature Usage")
plt.title("Feature Usage Over Generations")
plt.legend()
plt.grid(True)
plt.tight_layout()
plt.show()

print("Symbolic Variable Mapping:")
for symbol, name in symbolic_variable_map.items():
     print(f"{symbol} → {name}")

## pareto font (final generation)

# pareto_front = get_pareto_front(final_pop)

# print("\nPareto Front:")

# # path
# pareto_output_path = '/content/drive/My Drive/GWL/r2_complexity/train219_val99_1obj_r2 of GP/train219_pareto_front.txt'

# # txt file writing
# with open(pareto_output_path, 'w') as f:
#     f.write("Pareto Front:\n")
#     for ind in pareto_front:
#         line = f"R²: {ind.r2:.4f}, Complexity: {ind.complexity:.4f}, Expr: {ind.readable}\n"
#         print(line.strip())
#         f.write(line)

## Remove duplicate Pareto solutions based on R² and Complexity
"""

def remove_duplicate_pareto(front):

    unique = []
    seen = set()

    for ind in front:
        key = (ind.r2, ind.complexity)

        if key not in seen:
            seen.add(key)
            unique.append(ind)

    return unique

pareto = get_pareto_front(final_pop)


pareto_unique = remove_duplicate_pareto(pareto)

print("\nPareto Front (Duplicates Removed):")
for ind in pareto_unique:
    expr = ind.tree.to_readable_string(symbolic_variable_map)
    print(f"R²: {ind.r2:.4f}, Complexity: {ind.complexity:.4f}, Expr: {expr}")

txt_path = "/content/drive/My Drive/GWL/r2_complexity/train99_val219_2obj of GP/pareto_front_without_duplicates.txt"

with open(txt_path, "w", encoding="utf-8") as f:
    f.write("Pareto Front (Duplicates Removed)\n\n")

    for ind in pareto_unique:
        expr = ind.tree.to_readable_string(symbolic_variable_map)
        f.write(
            f"R²: {ind.r2:.6f}, "
            f"Complexity: {ind.complexity:.6f}, "
            f"Expr: {expr}\n"
        )

print(f"\nPareto front saved to: {txt_path}")

"""

## knee solution

# def find_knee_solution(pareto_front):
#     # Sort by complexity (x), extract (x, y)
#     pareto_sorted = sorted(pareto_front, key=lambda ind: ind.complexity)
#     xs = np.array([ind.complexity for ind in pareto_sorted])
#     ys = np.array([ind.r2 for ind in pareto_sorted])

#     # Line from first to last point
#     p1 = np.array([xs[0], ys[0]])
#     p2 = np.array([xs[-1], ys[-1]])

#     # Compute distances to the line
#     def perpendicular_distance(x, y):
#         vec = p2 - p1
#         point = np.array([x, y])
#         return np.abs((vec[0]) * (p1[1] - point[1]) - (vec[1]) * (p1[0] - point[0])) / np.linalg.norm(vec)


#     distances = [perpendicular_distance(x, y) for x, y in zip(xs, ys)]
#     knee_index = int(np.argmax(distances))
#     return pareto_sorted[knee_index]


# knee = find_knee_solution(pareto_front)

# # Console output
# knee_summary = f"\nKnee Solution:\nR²: {knee.r2:.4f}, Complexity: {knee.complexity:.4f}, Expr: {knee.readable}"
# print(knee_summary)

# # Save to .txt file
# knee_txt_path = '/content/drive/My Drive/GWL/r2_complexity/train219_val99_1obj_r2 of GP/train219_knee_solution.txt'  # Change path if needed
# with open(knee_txt_path, 'w') as f:
#     f.write(knee_summary)

# ### knee solution prediction save in excel and plot

# def export_predictions_to_excel(individual, filename="train_2obj_knee_predictions.xlsx"):
#     y_true = individual.y
#     try:
#         y_pred = [individual.tree.evaluate(row) for row in individual.X]
#     except Exception:
#         y_pred = [None] * len(individual.y)

#     df = pd.DataFrame({
#         "Actual": y_true,
#         "Predicted": y_pred
#     })

#     df.to_excel(filename, index=False, float_format="%.10f")
#     print(f"Predictions exported to: {filename}")

# export_predictions_to_excel(knee, "/content/drive/My Drive/GWL/r2_complexity/train219_val99_1obj_r2 of GP/train219_2obj_knee_predictions.xlsx")

# import matplotlib.pyplot as plt
# import numpy as np

# def plot_knee_predictions(knee_individual):
#     y_true = knee_individual.y
#     y_pred = [knee_individual.tree.evaluate(row) for row in knee_individual.X]

#     # Convert to numpy arrays for plotting
#     y_true = np.array(y_true)
#     y_pred = np.array(y_pred)

#     # Plot
#     plt.figure(figsize=(8, 6))
#     plt.scatter(y_true, y_pred, alpha=0.7)
#     plt.plot([y_true.min(), y_true.max()], [y_true.min(), y_true.max()], 'r--', lw=2)
#     plt.xlabel("Actual Target")
#     plt.ylabel("Predicted Value")
#     plt.title("Knee Solution: Target vs. Predicted")
#     plt.grid(True)
#     plt.tight_layout()
#     plt.show()

# plot_knee_predictions(knee)

# for ind in sorted(pareto_front, key=lambda x: -x.r2):
#     if ind.r2 > 0:
#         print(f"R²: {ind.r2:.4f}, Complexity: {ind.complexity:.4f}, Expr: {ind.readable}")

# plot pareto Front

# import matplotlib.pyplot as plt
# import numpy as np

# def plot_pareto_front(pareto_front, knee_individual=None):
#     # Extract complexity (x) and R² (y)
#     complexities = [ind.complexity for ind in pareto_front]
#     r2_scores = [ind.r2 for ind in pareto_front]

#     # Plot Pareto front
#     plt.figure(figsize=(10, 6))
#     plt.scatter(complexities, r2_scores, label='Pareto Front', s=60)

#     # Highlight knee if provided
#     if knee:
#         plt.scatter(knee.complexity, knee.r2, color='red', s=100, label='Knee Point')
#         plt.annotate('Knee', (knee.complexity, knee.r2),
#                      textcoords="offset points", xytext=(0,10), ha='center', color='red')

#     plt.xlabel("Expression Complexity (Size)")
#     plt.ylabel("R² Score")
#     plt.title("Pareto Front with Knee Solution")
#     plt.legend()
#     plt.grid(True)
#     plt.tight_layout()
#     plt.show()

# plot_pareto_front(pareto_front, knee)

# def find_weighted_best_solution(pareto_front, alpha=1.0, beta=0.05):
#     def score(ind):
#         return alpha * ind.r2 - beta * ind.complexity
#     return max(pareto_front, key=score)

# # Usage:
# weighted_best = find_weighted_best_solution(pareto_front, alpha=1.0, beta=0.05)
# print(f"\nWeighted Best Solution:\nR²: {weighted_best.r2:.4f}, Size: {weighted_best.complexity}, Expr: {weighted_best.readable}")

###Plot feature vs target data --tarin219_dataset.csv

import matplotlib.pyplot as plt


fig, axes = plt.subplots(nrows=4, ncols=2, figsize=(14, 12))
axes = axes.ravel()

for i, feature in enumerate(FEATURE_COLUMNS):
    axes[i].scatter(df[feature], df[TARGET_COLUMN], alpha=0.6)
    axes[i].set_title(f"{feature} vs {TARGET_COLUMN}")
    axes[i].set_xlabel(feature)
    axes[i].set_ylabel(TARGET_COLUMN)

plt.tight_layout()
plt.show()

###Plot feature vs target data GW_potential_8Indicator_318pointsData.xlsx

from google.colab import drive
drive.mount('/content/drive')
file_path = "/content/drive/My Drive/GWL/r2_complexity/train219_val99_1obj_r2 of GP/GW_potential_8Indicator_318pointsData.xlsx"
import pandas as pd
df = pd.read_excel(file_path)
df.head()

print(df.columns.tolist())


FEATURE_COLUMNS = ['LULC', 'drainage_density', 'geomorphology', 'Soil', 'Slope', 'Rain', 'lithology', 'lineament_density']
TARGET_COLUMN = 'validation point raw data'

#Plot feature vs target
fig, axes = plt.subplots(nrows=4, ncols=2, figsize=(14, 12))
axes = axes.ravel()

for i, feature in enumerate(FEATURE_COLUMNS[:8]):  # Only plot 8 indicators
    axes[i].scatter(df[feature], df[TARGET_COLUMN], alpha=0.6)
    axes[i].set_title(f"{feature} vs {TARGET_COLUMN}")
    axes[i].set_xlabel(feature)
    axes[i].set_ylabel(TARGET_COLUMN)

plt.tight_layout()
plt.show()


#df = pd.read_excel("content/drive/My Drive/GWL/r2_complexity/train219_val99_2obj of GP/GW_potential_8Indicator_318pointsData.xls")

from google.colab import drive
import pandas as pd

# Mount Google Drive
drive.mount('/content/drive')

## extract validation test99 datasets

#file paths
full_data_path = '/content/drive/My Drive/GWL/r2_complexity/train219_val99_1obj_r2 of GP/GW_potential_8Indicator_318pointsData.xlsx'
training_data_path = '/content/drive/My Drive/GWL/r2_complexity/train219_val99_1obj_r2 of GP/train219_dataset.csv'

#Load datasets
df_full = pd.read_excel(full_data_path)
df_train = pd.read_csv(training_data_path)

#Choose key columns for comparison
key_columns = ['FID']

#Drop duplicates and perform anti-join
df_full_unique = df_full.drop_duplicates(subset=key_columns)
df_train_unique = df_train.drop_duplicates(subset=key_columns)

df_validation = df_full_unique[~df_full_unique['FID'].isin(df_train_unique['FID'])]



validation_output_path = '/content/drive/My Drive/GWL/r2_complexity/train219_val99_1obj_r2 of GP/validation_test99_dataset.csv'
df_validation.to_csv(validation_output_path, index=False)

##### Single Run ------- Old version

import re

pareto_file_path = '/content/drive/My Drive/GWL/r2_complexity/train219_val99_1obj_r2 of GP/best_r2_individual.txt'


parsed_expressions = []

with open(pareto_file_path, 'r') as file:
    for line in file:
        #print("READ LINE:", line.strip())  # See what’s being read
        #match = re.match(r"R²:\s*([-\d.]+),\s*Complexity:\s*(\d+),\s*Expr:\s*(.+)", line.strip())
        match = re.match(r"R²:\s*([-\d.]+),\s*Complexity:\s*([-\d.]+),\s*Expr:\s*(.+)", line.strip())

        if match:
            r2 = float(match.group(1))
            complexity = float(match.group(2))
            expression = match.group(3).strip()
            parsed_expressions.append({
                "r2": r2,
                "complexity": complexity,
                "expression": expression
            })

# Preview parsed expressions
for exp in parsed_expressions:
    print(exp)

##### Single Run ------- Old version

##tree root



# Parse prefix expression to Node tree
def parse_prefix(expr_str):
    tokens = expr_str.replace('(', ' ( ').replace(')', ' ) ').replace(',', ' ').split()

    def parse_tokens(tokens):
        if not tokens:
            return None
        token = tokens.pop(0)
        if token in OPERATORS:
            func, arity = OPERATORS[token]
            children = [parse_tokens(tokens) for _ in range(arity)]
            return Node(token, children)
        elif token not in ['(', ')']:
            return Node(token)
        else:
            return parse_tokens(tokens)  # skip parens or commas

    return parse_tokens(tokens)


# Convert expressions to trees
# Parse prefix trees BEFORE writing Excel
for i, exp in enumerate(parsed_expressions):
    exp['tree'] = parse_prefix(exp['expression'])
    #print(f"[Expr {i+1}] Tree root: {exp['tree'].name}, Expression: {exp['expression']}")
    print(f"[Expr {i+1}] Loaded expression: {exp['expression']}")

##### Single Run ------- Old version


import pandas as pd
import numpy as np
from sklearn.metrics import r2_score
from sklearn.metrics import mean_squared_error
from sklearn.metrics import mean_absolute_error

validation_path = '/content/drive/My Drive/GWL/r2_complexity/train219_val99_1obj_r2 of GP/validation_test99_dataset.csv'
output_excel_path = '/content/drive/My Drive/GWL/r2_complexity/train219_val99_1obj_r2 of GP/best_r2_results.xlsx'


FEATURE_COLUMNS = ['Soil', 'Slope', 'Rain', 'LULC', 'lithology', 'lineament_density', 'geomorphology', 'drainage_density']
TARGET_COLUMN = 'validation point raw data'

# Map feature names to indices
feature_map = {name: idx for idx, name in enumerate(FEATURE_COLUMNS)}

# Load validation data
df_val = pd.read_csv(validation_path)
X_val = df_val[FEATURE_COLUMNS].values
y_val = df_val[TARGET_COLUMN].values


with pd.ExcelWriter(output_excel_path, engine='openpyxl') as writer:
    for i, exp in enumerate(parsed_expressions):
        preds = []
        print(f"\n[Expr {i+1}] {exp['expression']}")

        # Custom feature mapping just for Expr 5
        custom_map = feature_map.copy()
        if i == 4:  # Expr 5 is at index 4 (0-based)
            custom_map['lineament'] = custom_map['lineament_density']

        for idx, row in enumerate(X_val):
            try:
                pred = exp['tree'].evaluate(row, custom_map)
            except Exception as e:
                if idx == 0:
                    print(f"[Expr {i+1}] Evaluation error on first row: {e}")
                pred = None
            preds.append(pred)

        exp['predictions'] = preds

        # Compute R²
        try:
            r2_val = r2_score(y_val, preds)

        except:
            r2_val = -np.inf

        # Compute MSE, RMSE, MAE to console
        valid_pairs = [(y, p) for y, p in zip(y_val, preds) if p is not None and not np.isnan(p)]
        if valid_pairs:
            y_clean, preds_clean = zip(*valid_pairs)
            mse_val = mean_squared_error(y_clean, preds_clean)
            rmse_val = np.sqrt(mse_val)
            mae_val = mean_absolute_error(y_clean, preds_clean)
        else:
            mse_val = rmse_val = mae_val = np.nan

        #print(f"R2 (validation datasets): {r2_val:.4f} MSE: {mse_val:.4f}, RMSE: {rmse_val:.4f}, MAE: {mae_val:.4f}")
        #train_r2 = pareto_front[i].r2  # for training R²
        train_r2 = exp["r2"]  # already available from parsed_expressions
        print(f"R2 (train): {train_r2:.4f} \nR2 (validation): {r2_val:.4f} \nMSE: {mse_val:.4f}, RMSE: {rmse_val:.4f}, MAE: {mae_val:.4f}")

        # Combine features, actual, and predicted
        df_result = df_val[FEATURE_COLUMNS].copy()
        df_result['Actual'] = y_val
        df_result['Predicted'] = preds

        # Add header with R² and complexity and expression
        header_df = pd.DataFrame({
            f'R²: {r2_val:.4f}, Complexity: {exp["complexity"]}, Expression: {exp["expression"]}': []
        })

        # Write to sheet
        sheet_name = f'Expr_{i+1}'
        header_df.to_excel(writer, sheet_name=sheet_name, index=False)
        df_result.to_excel(writer, sheet_name=sheet_name, index=False, startrow=2)